# Generated by Django 4.2 on 2024-09-25 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.CharField(editable=False, max_length=100, verbose_name='Descripción'),
        ),
    ]
