# Generated by Django 4.2 on 2024-09-20 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estado', '0001_initial'),
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código')),
                ('fecha', models.DateField(verbose_name='Fecha y Hora')),
                ('descripcion', models.CharField(max_length=100, verbose_name='Descripción')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cliente.cliente', verbose_name='Cliente')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estado.estado', verbose_name='Estado')),
            ],
            options={
                'verbose_name_plural': 'Pedidos',
            },
        ),
    ]
